#!/bin/bash

cat > .env <<EOF
APP_NAME=${APP_NAME:-BovWeightCR}
APP_ENV=${APP_ENV:-production}
APP_KEY=${APP_KEY}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=${APP_URL:-http://localhost}
APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US
APP_MAINTENANCE_DRIVER=file

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=error

DB_CONNECTION=${DB_CONNECTION}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

SESSION_DRIVER=${SESSION_DRIVER:-file}
SESSION_LIFETIME=${SESSION_LIFETIME:-120}
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=${FILESYSTEM_DISK:-local}
QUEUE_CONNECTION=${QUEUE_CONNECTION:-sync}

CACHE_STORE=${CACHE_STORE:-file}

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="noreply@bovweightcr.com"
MAIL_FROM_NAME="${APP_NAME}"

ML_SERVICE_BASE_URL=${ML_SERVICE_BASE_URL:-https://unranked-mystified-thesaurus.ngrok-free.dev}
ML_SERVICE_ENDPOINT=${ML_SERVICE_ENDPOINT:-/api/v1/predict-weight}
ML_SERVICE_TIMEOUT=${ML_SERVICE_TIMEOUT:-15}

R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_REGION=${R2_REGION:-auto}
R2_BUCKET=${R2_BUCKET}
R2_ENDPOINT=${R2_ENDPOINT}
R2_URL=${R2_URL:-${R2_ENDPOINT}}
R2_USE_PATH_STYLE_ENDPOINT=${R2_USE_PATH_STYLE_ENDPOINT:-true}

VITE_APP_NAME="${APP_NAME}"
EOF

exec php -c /app/php.ini -S "0.0.0.0:${PORT:-8080}" -t /app/public /app/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php
